// @ts-nocheck
const token = document.querySelector('meta[name="bac9-editor-token"]').content;
const $ = (id) => document.getElementById(id);
const today = new Date().toISOString().slice(0, 10);
const state = { lang: 'en', mode: 'new', articles: [], drafts: [], document: makeDocument('') };
function blankArticle(lang, translationId) { return { id: '', translationId: translationId || '', lang: lang, title: '', description: '', category: 'business', tags: [], difficulty: 'beginner', published: today, updated: today, readTime: 10, heroImage: '', related: [], draft: false, body: '' }; }
function makeDocument(translationId) { return { translationId: translationId || '', en: blankArticle('en', translationId), ar: blankArticle('ar', translationId) }; }
async function api(path, options) { const opts = options || {}; const response = await fetch(path, { ...opts, headers: { 'content-type': 'application/json', 'x-bac9-token': token, ...(opts.headers || {}) } }); const data = await response.json().catch(() => ({ ok: false, error: 'The editor server returned an invalid response.' })); if (!response.ok && !data.validation && !data.pushFailed) throw new Error(data.error || 'Editor request failed.'); return data; }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function safeHref(value) { const href = String(value || '').trim(); return /^(?:https?:\/\/|mailto:|\/)/i.test(href) ? href : '#'; }
function inlineMarkdown(value) { let html = escapeHtml(value); html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, (_, alt, href) => { const safe = safeHref(href); return safe === '#' ? escapeHtml('[' + alt + '](' + href + ')') : '<img src="' + escapeHtml(safe) + '" alt="' + escapeHtml(alt) + '">'; }); html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, href) => '<a href="' + escapeHtml(safeHref(href)) + '" target="_blank" rel="noreferrer">' + label + '</a>'); html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/__([^_]+)__/g, '<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*(?!\*)/g, '<em>$1</em>').replace(/(?<!_)_([^_]+)_(?!_)/g, '<em>$1</em>').replace(/\x60([^\x60]+)\x60/g, '<code>$1</code>'); return html; }
function renderMarkdown(source) {
  const raw = String(source || '').replace(/\r\n/g, '\n'), lines = raw.split('\n'), html = []; let inCode = false, code = [], listType = null;
  const hasMdx = /(?:^import\s|<([A-Z][A-Za-z0-9]*)\b|export\s+(?:default\s+)?)/m.test(raw);
  const closeList = () => { if (listType) { html.push('</' + listType + '>'); listType = null; } };
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index], next = lines[index + 1] || '';
    if (/^\s*\x60\x60\x60/.test(line)) { if (inCode) { html.push('<pre><code>' + escapeHtml(code.join('\n')) + '</code></pre>'); code = []; inCode = false; } else { closeList(); inCode = true; } continue; }
    if (inCode) { code.push(line); continue; }
    if (/^\s*(?:import|export)\s/.test(line) || /<([A-Z][A-Za-z0-9]*)\b/.test(line)) { closeList(); html.push('<div class="preview-warning">MDX-only syntax is shown as a warning and is not executed in this preview.</div>'); continue; }
    if (!line.trim()) { closeList(); continue; }
    if (/^\s*\|/.test(line) && /^\s*\|?\s*:?-{3,}/.test(next)) { closeList(); const headers = line.split('|').map((cell) => cell.trim()).filter(Boolean), rows = []; index += 2; while (index < lines.length && /^\s*\|/.test(lines[index])) { rows.push(lines[index].split('|').map((cell) => cell.trim()).filter(Boolean)); index += 1; } index -= 1; html.push('<table><thead><tr>' + headers.map((cell) => '<th>' + inlineMarkdown(cell) + '</th>').join('') + '</tr></thead><tbody>' + rows.map((row) => '<tr>' + headers.map((_, i) => '<td>' + inlineMarkdown(row[i] || '') + '</td>').join('') + '</tr>').join('') + '</tbody></table>'); continue; }
    const heading = line.match(/^(#{1,6})\s+(.+)$/); if (heading) { closeList(); const level = Math.min(heading[1].length, 3); html.push('<h' + level + '>' + inlineMarkdown(heading[2]) + '</h' + level + '>'); continue; }
    const list = line.match(/^\s*([-*+] |\d+\. )(.+)$/); if (list) { const type = /^\d/.test(list[1]) ? 'ol' : 'ul'; if (listType && listType !== type) closeList(); if (!listType) { listType = type; html.push('<' + type + '>'); } html.push('<li>' + inlineMarkdown(list[2]) + '</li>'); continue; }
    if (/^\s*>/.test(line)) { closeList(); html.push('<blockquote>' + inlineMarkdown(line.replace(/^\s*>\s?/, '')) + '</blockquote>'); continue; }
    if (/^\s*([-*_])(?:\s*\1){2,}\s*$/.test(line)) { closeList(); html.push('<hr>'); continue; }
    closeList(); html.push('<p>' + inlineMarkdown(line) + '</p>');
  }
  if (inCode) html.push('<pre><code>' + escapeHtml(code.join('\n')) + '</code></pre>'); closeList(); return { html: html.join(''), hasMdx: hasMdx };
}
function sharedFromForm() { state.document.translationId = $('translationId').value.trim(); ['en', 'ar'].forEach((lang) => { const article = state.document[lang]; article.translationId = state.document.translationId; article.category = $('category').value; article.difficulty = $('difficulty').value; article.published = $('published').value; article.updated = $('updated').value; article.readTime = Number($('readTime').value); article.tags = $('tags').value.split(',').map((item) => item.trim()).filter(Boolean); article.related = $('related').value.split(',').map((item) => item.trim()).filter(Boolean); }); }
function languageToForm() { sharedFromForm(); const article = state.document[state.lang]; $('translationId').value = state.document.translationId || ''; $('category').value = article.category || 'business'; $('difficulty').value = article.difficulty || 'beginner'; $('published').value = article.published || today; $('updated').value = article.updated || today; $('readTime').value = article.readTime || 10; $('tags').value = (article.tags || []).join(', '); $('related').value = (article.related || []).join(', '); $('id').value = article.id || ''; $('heroImage').value = article.heroImage || ''; $('title').value = article.title || ''; $('description').value = article.description || ''; $('body').value = article.body || ''; $('language-eyebrow').textContent = state.lang === 'en' ? 'ENGLISH VERSION' : 'ARABIC VERSION'; $('language-heading').textContent = state.lang === 'en' ? 'English tutorial' : 'النسخة العربية'; $('body').dir = state.lang === 'ar' ? 'rtl' : 'ltr'; renderPreviewOnly(); updateStatuses(); }
function formToLanguage() { const article = state.document[state.lang]; article.id = $('id').value.trim(); article.heroImage = $('heroImage').value.trim(); article.title = $('title').value.trim(); article.description = $('description').value.trim(); article.body = $('body').value; sharedFromForm(); updateStatuses(); }
function updateStatuses() { ['en', 'ar'].forEach((lang) => { const article = state.document[lang]; $(lang + '-status').style.color = article.id && article.title && article.body.trim() ? 'var(--accent)' : 'var(--warning)'; }); }
function showFeedback(title, errors, warnings, success) { $('feedback-panel').hidden = false; $('feedback-title').textContent = title; const lines = (errors || []).map((item) => '<div class="feedback-line error">✕ ' + escapeHtml(item) + '</div>').concat((warnings || []).map((item) => '<div class="feedback-line warning">△ ' + escapeHtml(item) + '</div>')); if (success) lines.push('<div class="feedback-line success">✓ ' + escapeHtml(success) + '</div>'); $('feedback').innerHTML = lines.join('') || '<div class="feedback-line success">✓ No issues found.</div>'; $('feedback-panel').scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
function renderPreviewOnly() { const result = renderMarkdown($('body').value); $('preview').innerHTML = result.html || '<p class="muted">Your preview will appear here.</p>'; $('mdx-warning').textContent = result.hasMdx ? 'MDX syntax detected' : ''; }
function renderPreview() { formToLanguage(); renderPreviewOnly(); }
function documentForApi() { formToLanguage(); return JSON.parse(JSON.stringify(state.document)); }
async function loadArticles() { const data = await api('/api/articles'); state.articles = data.articles || []; renderSidebar(); }
async function loadDrafts() { const data = await api('/api/drafts'); state.drafts = data.drafts || []; renderSidebar(); }
function renderSidebar() { const query = ($('article-search').value || '').toLowerCase(), list = state.articles.filter((item) => JSON.stringify(item).toLowerCase().includes(query)); $('article-list').innerHTML = list.length ? list.map((item) => '<button class="article-item' + (state.mode === 'existing' && state.document.translationId === item.translationId ? ' active' : '') + '" data-translation-id="' + escapeHtml(item.translationId) + '"><strong>' + escapeHtml(item.en?.title || item.ar?.title || item.translationId) + '</strong><small>' + escapeHtml(item.translationId) + ' · ' + (item.en && item.ar ? 'EN + AR' : 'incomplete') + '</small></button>').join('') : '<div class="empty">No tutorials found.</div>'; $('draft-list').innerHTML = state.drafts.length ? state.drafts.map((draft) => '<button class="draft-item' + (state.mode === 'draft' && state.document.translationId === draft.translationId ? ' active' : '') + '" data-draft-id="' + escapeHtml(draft.translationId) + '"><strong>' + escapeHtml(draft.title) + '</strong><small>' + escapeHtml(draft.translationId) + '</small></button>').join('') : '<div class="empty">No private drafts yet.</div>'; document.querySelectorAll('[data-translation-id]').forEach((button) => button.addEventListener('click', () => openExisting(button.dataset.translationId))); document.querySelectorAll('[data-draft-id]').forEach((button) => button.addEventListener('click', () => openDraft(button.dataset.draftId))); }
async function openExisting(translationId) { const data = await api('/api/articles/' + encodeURIComponent(translationId)); state.document = data.document; state.mode = 'existing'; $('mode-label').textContent = 'EDITING EXISTING TUTORIAL'; $('editor-title').textContent = state.document.en?.title || state.document.ar?.title || translationId; languageToForm(); renderSidebar(); }
async function openDraft(translationId) { const data = await api('/api/drafts/' + encodeURIComponent(translationId)); state.document = data.document; state.mode = 'draft'; $('mode-label').textContent = 'PRIVATE DRAFT'; $('editor-title').textContent = state.document.en?.title || state.document.ar?.title || 'Private draft'; languageToForm(); renderSidebar(); }
function newTutorial() { state.document = makeDocument(''); state.mode = 'new'; $('mode-label').textContent = 'NEW TUTORIAL'; $('editor-title').textContent = 'Create a bilingual tutorial'; languageToForm(); renderSidebar(); }
async function saveDraft() { $('save-state').textContent = 'Saving…'; try { const data = await api('/api/drafts', { method: 'POST', body: JSON.stringify({ document: documentForApi() }) }); state.mode = 'draft'; $('save-state').textContent = 'Draft saved locally'; await loadDrafts(); showFeedback('Draft saved', [], [], 'Saved privately under .bac9-drafts/' + data.translationId + '/. Nothing was committed or pushed.'); } catch (error) { $('save-state').textContent = 'Save failed'; showFeedback('Draft could not be saved', [error.message]); } }
async function validate() { try { const data = await api('/api/validate', { method: 'POST', body: JSON.stringify({ document: documentForApi() }) }); showFeedback(data.ok ? 'Validation passed' : 'Validation found issues', (data.validation && data.validation.errors) || [data.error].filter(Boolean), (data.validation && data.validation.warnings) || [], data.ok ? 'Both language documents are ready for the publish checks.' : ''); return data.ok; } catch (error) { showFeedback('Validation failed', [error.message]); return false; } }
async function publish() { if (state.mode === 'existing' && !window.confirm('This will overwrite the selected tutorial files after validation. Continue?')) return; const document = documentForApi(); $('save-state').textContent = 'Validating and building…'; try { const data = await api('/api/publish', { method: 'POST', body: JSON.stringify({ document: document, expectedHashes: { en: document.en.sourceHash, ar: document.ar.sourceHash } }) }); if (data.ok) { $('save-state').textContent = 'Published'; showFeedback('Published successfully', [], [], 'Commit ' + (data.commitHash || '') + ' was pushed to main. GitHub Actions: ' + (data.actionsUrl || 'workflow link unavailable')); await loadArticles(); return; } if (data.pushFailed) { showFeedback('Push failed after a successful local commit', [data.error], [], 'Commit ' + data.commitHash + ' is available locally. Use Retry push below when the remote connection is ready.'); const retry = document.createElement('button'); retry.className = 'button primary'; retry.textContent = 'Retry push'; retry.onclick = async () => { const result = await api('/api/push', { method: 'POST', body: JSON.stringify({ commitHash: data.commitHash }) }); showFeedback(result.ok ? 'Push succeeded' : 'Push failed', result.ok ? [] : [result.error], [], result.ok ? 'Commit ' + result.commitHash + ' was pushed. GitHub Actions: ' + (result.actionsUrl || 'workflow link unavailable') : ''); }; $('feedback').appendChild(retry); return; } showFeedback('Publish stopped', (data.validation && data.validation.errors) || [data.error].filter(Boolean), (data.validation && data.validation.warnings) || [], data.output ? 'The validation command reported: ' + data.output.slice(-900) : ''); $('save-state').textContent = 'Publish stopped'; } catch (error) { $('save-state').textContent = 'Publish failed'; showFeedback('Publish failed', [error.message]); } }
async function upload(file) { try { const data = await api('/api/normalize', { method: 'POST', body: JSON.stringify({ lang: state.lang, source: await file.text(), fallback: state.document[state.lang] }) }); state.document[state.lang] = { ...state.document[state.lang], ...data.article, lang: state.lang, translationId: state.document.translationId || data.article.translationId || '' }; languageToForm(); showFeedback('Import complete', [], data.warnings || [], 'Review the metadata and both language tabs before publishing.'); } catch (error) { showFeedback('Import failed', [error.message]); } }
document.querySelectorAll('.language-tab').forEach((button) => button.addEventListener('click', () => { formToLanguage(); state.lang = button.dataset.lang; document.querySelectorAll('.language-tab').forEach((item) => item.classList.toggle('active', item === button)); languageToForm(); }));
['translationId', 'category', 'difficulty', 'published', 'updated', 'readTime', 'tags', 'related', 'id', 'heroImage', 'title', 'description'].forEach((id) => $(id).addEventListener('input', () => { languageToForm(); $('save-state').textContent = 'Unsaved changes'; }));
$('body').addEventListener('input', () => { renderPreview(); $('save-state').textContent = 'Unsaved changes'; }); $('upload').addEventListener('change', (event) => event.target.files[0] && upload(event.target.files[0])); $('new-button').addEventListener('click', newTutorial); $('refresh-button').addEventListener('click', () => Promise.all([loadArticles(), loadDrafts()])); $('article-search').addEventListener('input', renderSidebar); $('draft-button').addEventListener('click', saveDraft); $('validate-button').addEventListener('click', validate); $('publish-button').addEventListener('click', publish); $('close-feedback').addEventListener('click', () => { $('feedback-panel').hidden = true; });
Promise.all([loadArticles(), loadDrafts()]).then(() => languageToForm()).catch((error) => showFeedback('Could not load the editor', [error.message]));
